import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const source = readFileSync(new URL('./ai-designer-revision-loop-v2.js', import.meta.url), 'utf8');
assert.match(source, /AI 真实理解结果/);
assert.match(source, /DeepSeek analysis v/);
assert.match(source, /prepareContentRevision/);
assert.match(source, /generateContentRevision/);
assert.match(source, /content_ready 后仅 AI 设计师账号自动调用生成/);
assert.match(source, /历次修改记录/);
assert.match(source, /首次流程进度继续保留在顶部/);
assert.match(source, /AI 已向需求方追问/);
assert.doesNotMatch(source, /getElementById\('pipeline'\)/);
assert.doesNotMatch(source, /pipeline\.innerHTML/);
console.log('ai designer revision loop v2: 10/10 passed');
