import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const source = readFileSync(new URL('./requester-framework-revision-flow-v3.js', import.meta.url), 'utf8');
const legacy = readFileSync(new URL('./requester-framework-revision-flow-v2.js', import.meta.url), 'utf8');
assert.match(source, /提交补充信息给 AI 设计师/);
assert.match(source, /我已更新腾讯文档，请 AI 设计师同时读取最新内容/);
assert.match(source, /submitContentRevisionRequest/);
assert.match(source, /需求方只负责补充需求信息/);
assert.match(source, /不会创建 Seedream generation/);
assert.match(source, /content_revision_waiting_ai/);
assert.doesNotMatch(source, /generateContentRevision/);
assert.doesNotMatch(source, /generateFrameworkRevision/);
assert.doesNotMatch(source, /confirmAiUnderstanding/);
assert.doesNotMatch(source, /信息已补齐，生成 Demo/);
assert.doesNotMatch(source, /data-template-action="generate-/);
assert.match(legacy, /bootstrapRequesterFrameworkRevisionFlowV3/);
assert.doesNotMatch(legacy, /检测腾讯文档最新内容/);
assert.doesNotMatch(legacy, /分析内容变化（不生图）/);
assert.doesNotMatch(legacy, /data-template-action="generate-content"/);
console.log('requester revision flow permissions: 15/15 passed');
