import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const source = readFileSync(new URL('./requester-revision-loop-v1.js', import.meta.url), 'utf8');
assert.match(source, /满意，确认验收并结束/);
assert.match(source, /继续补充修改意见/);
assert.match(source, /第 \$\{Number\(revision\.revision_no/);
assert.match(source, /submitContentRevisionRequest/);
assert.match(source, /answer_content_revision_clarification/);
assert.doesNotMatch(source, /DeepSeek analysis v/);
assert.match(source, /请回答与当前修改有关的关键问题，AI 会继续设计/);
assert.match(source, /提交补充，继续让 AI 理解/);
assert.match(source, /data-revision-loop-root/);
assert.doesNotMatch(source, /generateContentRevision/);
assert.doesNotMatch(source, /generateFrameworkRevision/);
assert.doesNotMatch(source, /生成 Demo/);
console.log('requester revision loop: 12/12 passed');
