import { createClient } from 'npm:@supabase/supabase-js@2';
import { resolveDemoSize, selectGenerationPages, selectModelInputs } from '../uat-ai-design/generation-service.ts';
import { SEEDREAM_DEMO_MODEL } from '../uat-ai-design/seedream-client.ts';
import { buildCreativeDemoPrompt, DEMO_PROMPT_VERSION } from '../uat-seedream-demo-page/creative-prompt.ts';
import { isSafeConnectFailure, safeConnectRetry } from './worker-policy.mjs';

const BUILD='20260818-seedream-queue-worker-v1';
const GATEWAY='https://bjzfkwxrvytgphvgwltl.supabase.co/functions/v1/uat-ark-gateway';
const STALE_MS=10*60*1000;
const MAX_SCAN=12;
const json=(body:unknown,status=200)=>new Response(JSON.stringify({build:BUILD,...(body as any)}),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const env=(name:string)=>String(Deno.env.get(name)||'').trim();
async function readJson(response:Response){const text=await response.text().catch(()=>'');if(!text)return{};try{return JSON.parse(text)}catch{return{raw:text.slice(0,2000)}}}
function latestByPage(rows:any[]){const m=new Map<number,any>();for(const r of [...rows].sort((a,b)=>Date.parse(a.created_at||'')-Date.parse(b.created_at||'')))m.set(Number(r.page_index||1),r);return m}
function due(row:any){const t=Date.parse(String(row?.output?.next_attempt_at||''));return !Number.isFinite(t)||t<=Date.now()}
async function priorPagesReady(admin:any,row:any){const page=Number(row.page_index||1);if(page<=1)return true;const {data,error}=await admin.from('uat_design_generations').select('id,page_index,status,created_at').eq('task_id',row.task_id).eq('analysis_id',row.analysis_id).eq('kind','demo').eq('model',SEEDREAM_DEMO_MODEL).eq('prompt_version',DEMO_PROMPT_VERSION).lt('page_index',page).order('created_at',{ascending:true});if(error)throw error;const latest=latestByPage(data||[]);for(let p=1;p<page;p++){const r=latest.get(p);if(!r||!['ready','confirmed'].includes(String(r.status)))return false}return true}
async function cancelDownstream(admin:any,row:any,reason:string){const runId=String(row?.output?.run_id||'');let q=admin.from('uat_design_generations').update({status:'cancelled',error_message:reason,updated_at:new Date().toISOString()}).eq('task_id',row.task_id).eq('analysis_id',row.analysis_id).eq('kind','demo').eq('model',SEEDREAM_DEMO_MODEL).eq('prompt_version',DEMO_PROMPT_VERSION).gt('page_index',Number(row.page_index||1)).eq('status','queued');if(runId)q=q.contains('output',{run_id:runId});await q}
async function audit(admin:any,action:string,row:any,details:any={}){await admin.from('uat_audit_log').insert({actor_id:null,actor_email:'uat-seedream-worker@internal',action,task_id:row.task_id,details:{generation_id:row.id,page_index:row.page_index,...details}})}
async function finishFailure(admin:any,row:any,message:string,stage:string,extra:any={}){const output={...(row.output||{}),...extra,failure_stage:stage,worker_finished_at:new Date().toISOString()};await admin.from('uat_design_generations').update({status:'failed',error_message:message,output,updated_at:new Date().toISOString()}).eq('id',row.id);await cancelDownstream(admin,row,'PREVIOUS_PAGE_FAILED');await admin.from('test_tasks').update({status:'ready_for_demo',summary_desc:`P${row.page_index} 失败，已停止；成功页面保留，后续页未执行`}).eq('id',row.task_id);await audit(admin,'demo_worker_page_failed',row,{stage,error:message});return{generation_id:row.id,page_index:row.page_index,status:'failed',stage,error:message}}
async function markReady(admin:any,row:any,payload:any,page:any,pages:any[],refs:any[],assets:any[],inputs:any[]){const size=resolveDemoSize((await admin.from('uat_requirement_analyses').select('brief').eq('id',row.analysis_id).single()).data?.brief||{});const output={...(row.output||{}),provider:'seedream',model:String(payload.model||SEEDREAM_DEMO_MODEL),image_url:String(payload.drive_url||payload.provider_url||''),provider_url:String(payload.provider_url||'')||null,size,target_size:`${size.width}x${size.height}`,provider_size:String(payload.provider_requested_size||''),requested_size:String(payload.provider_requested_size||''),actual_size:String(payload.actual_size||''),dimension_match:true,input_image_count:Number(payload.input_image_count??inputs.length),drive_file_id:payload.drive_file_id||null,drive_url:payload.drive_url||null,drive_thumbnail_url:payload.drive_thumbnail_url||null,drive_folder_id:payload.drive_folder_id||null,drive_folder_url:payload.drive_folder_url||null,drive_file_name:payload.drive_file_name||null,drive_archive_status:'completed',persistent_storage:'google_drive',usage:payload.usage||{},page_index:row.page_index,page_count:pages.length,page_title:page.title,exact_copy:page.copy,prompt_version:DEMO_PROMPT_VERSION,style_reference_count:refs.length,design_asset_count:assets.length,model_input_count:inputs.length,failure_stage:null,next_attempt_at:null,worker_finished_at:new Date().toISOString()};await admin.from('uat_design_generations').update({status:'ready',error_message:null,output,usage:payload.usage||{},updated_at:new Date().toISOString()}).eq('id',row.id);const {data:readyRows}=await admin.from('uat_design_generations').select('page_index,status,created_at').eq('task_id',row.task_id).eq('analysis_id',row.analysis_id).eq('kind','demo').eq('model',SEEDREAM_DEMO_MODEL).eq('prompt_version',DEMO_PROMPT_VERSION).in('status',['ready','confirmed']).order('created_at',{ascending:true});const readyPages=new Set((readyRows||[]).map((r:any)=>Number(r.page_index))),complete=pages.every((p:any)=>readyPages.has(Number(p.index)));await admin.from('test_tasks').update({status:complete?'demo_review':'ready_for_demo',summary_desc:complete?`Seedream 4.0 Demo 已完成 ${pages.length}/${pages.length}，全部已归档 Google Drive`:`P${row.page_index} 已完成并归档 Google Drive；后台将继续下一页`}).eq('id',row.task_id);await audit(admin,'demo_worker_page_ready',row,{drive_file_id:payload.drive_file_id,complete});return{generation_id:row.id,page_index:row.page_index,status:'ready',complete}}

Deno.serve(async req=>{if(req.method!=='POST')return json({ok:false,error:'METHOD_NOT_ALLOWED'},405);const su=env('SUPABASE_URL'),sk=env('SUPABASE_SERVICE_ROLE_KEY');if(!su||!sk)return json({ok:false,error:'SERVER_ENV_MISSING'},500);const admin=createClient(su,sk,{auth:{persistSession:false,autoRefreshToken:false}});const secret=String(req.headers.get('x-seedream-worker-secret')||'').trim();const {data:authorized,error:authError}=await admin.rpc('validate_uat_seedream_worker_secret',{candidate:secret});if(authError||authorized!==true)return json({ok:false,error:'UNAUTHORIZED_WORKER'},401);
  const staleCutoff=new Date(Date.now()-STALE_MS).toISOString();const {data:stale}=await admin.from('uat_design_generations').select('*').eq('kind','demo').eq('model',SEEDREAM_DEMO_MODEL).eq('prompt_version',DEMO_PROMPT_VERSION).eq('status','generating').lt('updated_at',staleCutoff).limit(10);for(const row of stale||[]){await finishFailure(admin,row,'WORKER_STALE_PROVIDER_STATE_UNKNOWN','worker_stale',{provider_state_unknown:true})}
  const {data:queued,error:qError}=await admin.from('uat_design_generations').select('*').eq('kind','demo').eq('model',SEEDREAM_DEMO_MODEL).eq('prompt_version',DEMO_PROMPT_VERSION).eq('status','queued').order('created_at',{ascending:true}).limit(MAX_SCAN);if(qError)return json({ok:false,error:qError.message},500);let candidate:any=null;for(const row of queued||[]){if(!due(row))continue;if(await priorPagesReady(admin,row)){candidate=row;break}}if(!candidate)return json({ok:true,processed:0,queued:(queued||[]).length});
  const {data:claimed,error:claimError}=await admin.from('uat_design_generations').update({status:'generating',error_message:null,output:{...(candidate.output||{}),worker_started_at:new Date().toISOString()},updated_at:new Date().toISOString()}).eq('id',candidate.id).eq('status','queued').select('*').maybeSingle();if(claimError)return json({ok:false,error:claimError.message},500);if(!claimed)return json({ok:true,processed:0,skipped:'ALREADY_CLAIMED'});candidate=claimed;await audit(admin,'demo_worker_page_started',candidate,{build:BUILD});
  try{const [{data:analysis,error:aError},{data:refs,error:rError},{data:assets,error:dError}]=await Promise.all([admin.from('uat_requirement_analyses').select('*').eq('id',candidate.analysis_id).eq('task_id',candidate.task_id).single(),admin.from('uat_visual_references').select('id,file_name,data_url,note,is_primary,sort_order').eq('task_id',candidate.task_id).order('sort_order',{ascending:true}),admin.from('uat_design_assets').select('id,file_name,data_url,asset_role,note,sort_order').eq('task_id',candidate.task_id).order('sort_order',{ascending:true})]);if(aError||!analysis)throw new Error('ANALYSIS_NOT_FOUND');if(rError||dError)throw new Error((rError||dError)?.message||'DEMO_INPUT_READ_FAILED');const pages=selectGenerationPages(analysis.brief||{}),page=pages.find((p:any)=>Number(p.index)===Number(candidate.page_index));if(!page)throw new Error('DEMO_PAGE_NOT_FOUND');const references=refs||[],required=assets||[],inputs=selectModelInputs(references,required) as any[],styleReference=[...references].sort((a:any,b:any)=>Number(Boolean(b.is_primary))-Number(Boolean(a.is_primary))||Number(a.sort_order||0)-Number(b.sort_order||0))[0]||null,prompt=buildCreativeDemoPrompt({brief:analysis.brief||{},page,styleReference,assets:required}),size=resolveDemoSize(analysis.brief||{}),attempt=Number(candidate.output?.connect_attempts||0)+1;
    let response:Response;try{response=await fetch(GATEWAY,{method:'POST',headers:{authorization:`Bearer ${sk}`,'x-seedream-worker-secret':secret,'content-type':'application/json'},body:JSON.stringify({action:'seedream.generate',task_id:candidate.task_id,page_index:candidate.page_index,page_count:pages.length,width:size.width,height:size.height,prompt,images:inputs.map((x:any)=>x.data_url)}),signal:AbortSignal.timeout(300000)})}catch(error){return json({ok:true,processed:1,result:await finishFailure(admin,candidate,`WORKER_GATEWAY_STATE_UNKNOWN:${error instanceof Error?error.message:String(error)}`,'worker_gateway',{provider_state_unknown:true})})}
    const payload:any=await readJson(response);if(!response.ok||payload?.ok!==true){const message=String(payload?.error||`ARK_GATEWAY_HTTP_${response.status}`);if(isSafeConnectFailure(message)){const retry=safeConnectRetry(attempt);if(retry.retry){const output={...(candidate.output||{}),connect_attempts:attempt,next_attempt_at:retry.next_attempt_at,last_connect_error:message,worker_last_attempt_at:new Date().toISOString()};await admin.from('uat_design_generations').update({status:'queued',error_message:null,output,updated_at:new Date().toISOString()}).eq('id',candidate.id);await admin.from('test_tasks').update({status:'ready_for_demo',summary_desc:`P${candidate.page_index} Ark 网络连接失败，已安全排队重连 ${attempt}/3；未进入计费生成`}).eq('id',candidate.task_id);await audit(admin,'demo_worker_safe_connect_retry',candidate,{attempt,next_attempt_at:retry.next_attempt_at});return json({ok:true,processed:1,result:{generation_id:candidate.id,status:'queued',safe_connect_retry:true,attempt,next_attempt_at:retry.next_attempt_at}})}return json({ok:true,processed:1,result:await finishFailure(admin,candidate,message,'ark_connect',{connect_attempts:attempt})})}return json({ok:true,processed:1,result:await finishFailure(admin,candidate,message,'generation',{gateway_status:response.status})})}
    if(!payload?.drive_file_id){return json({ok:true,processed:1,result:await finishFailure(admin,candidate,String(payload?.drive_error||'GOOGLE_DRIVE_ARCHIVE_FAILED'),'drive_archive',{provider_generated:true,provider_url:payload?.provider_url||null,drive_archive_status:'failed'})})}
    return json({ok:true,processed:1,result:await markReady(admin,candidate,payload,page,pages,references,required,inputs)});
  }catch(error){return json({ok:true,processed:1,result:await finishFailure(admin,candidate,error instanceof Error?error.message:String(error),'worker')})}
});
