import { createClient } from 'npm:@supabase/supabase-js@2';
import { resolveDemoSize, selectGenerationPages, selectModelInputs } from '../uat-ai-design/generation-service.ts';
import { SEEDREAM_DEMO_MODEL } from '../uat-ai-design/seedream-client.ts';
import { SEEDREAM_40, SEEDREAM_45, SEEDREAM_50, isModelAllowedForMode } from '../uat-ai-design/content-revision-model-router.mjs';
import { buildCreativeDemoPrompt, DEMO_PROMPT_VERSION } from '../uat-seedream-demo-page/creative-prompt.ts';
import { buildTemplateRevisionPrompt, TEMPLATE_REVISION_PROMPT_VERSION } from '../uat-ai-design/template-revision-prompt.ts';
import { buildRevisionManifest } from '../uat-ai-design/framework-template-core.ts';
import { resolveGenerationStrategy } from './generation-strategy.mjs';
import { isSafeConnectFailure, safeConnectRetry } from './worker-policy.mjs';
import { buildFormalVersionPublication, formalAssetStoragePath } from './formal-version-publisher.mjs';

const BUILD='20260820-seedream-model-routing-v1';
const GATEWAY='https://bjzfkwxrvytgphvgwltl.supabase.co/functions/v1/uat-ark-gateway';
const DRIVE_RELAY='https://supffjeeouibhqdfqosk.supabase.co/functions/v1/uat-seedream-drive-relay';
const SUPPORTED_MODELS=[SEEDREAM_40,SEEDREAM_45,SEEDREAM_50];
const STALE_MS=10*60*1000;
const MAX_SCAN=20;
const encoder=new TextEncoder();
const json=(body:unknown,status=200)=>new Response(JSON.stringify({build:BUILD,...(body as any)}),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
const env=(name:string)=>String(Deno.env.get(name)||'').trim();
async function readJson(response:Response){const text=await response.text().catch(()=>'');if(!text)return{};try{return JSON.parse(text)}catch{return{raw:text.slice(0,2000)}}}
function mode(row:any){return String(row?.generation_mode||'initial_framework')}
function relevant(row:any){const m=mode(row),model=String(row?.model||'');return isModelAllowedForMode(m,model)&&((['initial_framework','framework_revision'].includes(m)&&String(row?.prompt_version||'')===DEMO_PROMPT_VERSION)||(m==='content_revision'&&String(row?.prompt_version||'')===TEMPLATE_REVISION_PROMPT_VERSION))}
function due(row:any){const t=Date.parse(String(row?.output?.next_attempt_at||''));return !Number.isFinite(t)||t<=Date.now()}
function outputOf(row:any){return row?.output&&typeof row.output==='object'?row.output:{}}
function groupField(row:any){const m=mode(row);return m==='content_revision'?'revision_id':m==='framework_revision'?'framework_adjustment_id':'analysis_id'}
function archiveNamespace(row:any){const group=row?.revision_id||row?.framework_adjustment_id||row?.analysis_id||row?.id||crypto.randomUUID();return `${String(row?.task_id||'task')}-${mode(row)}-${String(group).replace(/[^a-zA-Z0-9_-]/g,'').slice(0,8)}`}
async function groupRows(admin:any,row:any){const field=groupField(row),value=row?.[field];if(!value)return[];const {data,error}=await admin.from('uat_design_generations').select('*').eq('task_id',row.task_id).eq(field,value).order('page_index',{ascending:true});if(error)throw error;return(data||[]).filter(relevant)}
async function priorGroupReady(admin:any,row:any){const rows=await groupRows(admin,row),page=Number(row.page_index||1);return rows.filter((item:any)=>Number(item.page_index)<page).every((item:any)=>['ready','confirmed'].includes(String(item.status)))}
async function cancelDownstream(admin:any,row:any,reason:string){const field=groupField(row),value=row?.[field];if(!value)return;await admin.from('uat_design_generations').update({status:'cancelled',error_message:reason,updated_at:new Date().toISOString()}).eq('task_id',row.task_id).eq(field,value).gt('page_index',Number(row.page_index||1)).eq('status','queued')}
async function audit(admin:any,action:string,row:any,details:any={}){await admin.from('uat_audit_log').insert({actor_id:null,actor_email:'uat-seedream-worker@internal',action,task_id:row.task_id,details:{generation_id:row.id,generation_mode:mode(row),page_index:row.page_index,model:row.model,...details}})}
async function hmacHex(secret:string,value:string){const key=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const signed=await crypto.subtle.sign('HMAC',key,encoder.encode(value));return Array.from(new Uint8Array(signed),b=>b.toString(16).padStart(2,'0')).join('')}
function bytesToBase64(bytes:Uint8Array){let out='';const chunk=0x8000;for(let i=0;i<bytes.length;i+=chunk)out+=String.fromCharCode(...bytes.subarray(i,Math.min(i+chunk,bytes.length)));return btoa(out)}
async function drivePreviewDataUrl(admin:any,driveFileId:string){const {data,error}=await admin.rpc('get_uat_seedream_drive_relay_secret');const secret=String(data||'').trim();if(error||!secret)throw new Error('DRIVE_RELAY_SECRET_MISSING');const signature=await hmacHex(secret,'davis-seedream-drive-relay:v1');const response=await fetch(DRIVE_RELAY,{method:'POST',headers:{'content-type':'application/json','x-davis-relay-signature':signature},body:JSON.stringify({action:'preview',drive_file_id:driveFileId}),signal:AbortSignal.timeout(90000)});if(!response.ok)throw new Error(`TEMPLATE_DRIVE_PREVIEW_FAILED:${response.status}`);const mime=String(response.headers.get('content-type')||'image/jpeg').split(';')[0],bytes=new Uint8Array(await response.arrayBuffer());if(!bytes.length)throw new Error('TEMPLATE_DRIVE_PREVIEW_EMPTY');return`data:${mime};base64,${bytesToBase64(bytes)}`}
async function finishFailure(admin:any,row:any,message:string,stage:string,extra:any={}){const m=mode(row),output={...outputOf(row),...extra,failure_stage:stage,worker_finished_at:new Date().toISOString()};await admin.from('uat_design_generations').update({status:'failed',error_message:message,output,updated_at:new Date().toISOString()}).eq('id',row.id);await cancelDownstream(admin,row,'PREVIOUS_PAGE_FAILED');if(m==='content_revision'&&row.revision_id){await admin.from('uat_content_revisions').update({status:'failed'}).eq('id',row.revision_id);await admin.from('test_tasks').update({status:'reviewing',summary_desc:`内容改版生成失败：${message.slice(0,120)}；上一可验收版本仍保留`}).eq('id',row.task_id)}else{await admin.from('test_tasks').update({status:'rejected',summary_desc:`框架生成失败：${message.slice(0,120)}；等待需求方手动重试`}).eq('id',row.task_id)}await audit(admin,'seedream_worker_page_failed',row,{stage,error:message});return{generation_id:row.id,page_index:row.page_index,status:'failed',stage,error:message}}

function extensionForContentType(contentType:string){const value=String(contentType||'').toLowerCase();if(value.includes('jpeg'))return'jpg';if(value.includes('webp'))return'webp';if(value.includes('gif'))return'gif';return'png'}
function decodeImageDataUrl(value:string){const match=String(value||'').match(/^data:(image\/[a-z0-9.+-]+);base64,(.+)$/i);if(!match)throw new Error('FORMAL_ASSET_DATA_URL_INVALID');const binary=atob(match[2]),bytes=new Uint8Array(binary.length);for(let index=0;index<binary.length;index+=1)bytes[index]=binary.charCodeAt(index);return{contentType:match[1],bytes:bytes.buffer}}
async function persistFormalAsset(admin:any,row:any,payload:any){let contentType='image/png',bytes:ArrayBuffer|null=null;const source=String(payload?.provider_url||'').trim();if(source){try{const response=await fetch(source,{signal:AbortSignal.timeout(120000)});if(response.ok){contentType=String(response.headers.get('content-type')||'image/png').split(';')[0];if(contentType.startsWith('image/'))bytes=await response.arrayBuffer()}}catch{/* archived copy fallback below */}}if(!bytes&&payload?.drive_file_id){const decoded=decodeImageDataUrl(await drivePreviewDataUrl(admin,String(payload.drive_file_id)));contentType=decoded.contentType;bytes=decoded.bytes}if(!bytes)throw new Error('FORMAL_ASSET_SOURCE_UNAVAILABLE');if(!bytes.byteLength)throw new Error('FORMAL_ASSET_EMPTY');const path=formalAssetStoragePath({taskId:row.task_id,generationId:row.id,pageIndex:row.page_index,extension:extensionForContentType(contentType)});const uploaded=await admin.storage.from('designs').upload(path,bytes,{contentType,cacheControl:'31536000',upsert:true});if(uploaded.error)throw uploaded.error;const publicUrl=String(admin.storage.from('designs').getPublicUrl(path)?.data?.publicUrl||'').trim();if(!publicUrl.includes('/storage/v1/object/public/designs/'))throw new Error('FORMAL_ASSET_PUBLIC_URL_REQUIRED');return publicUrl}
async function publishFormalVersion(admin:any,publication:any){if(!publication)return false;const versionResult=await admin.from('design_versions').upsert(publication.version,{onConflict:'task_id,version_no'}).select('id').single();if(versionResult.error||!versionResult.data)throw versionResult.error||new Error('FORMAL_VERSION_UPSERT_FAILED');const versionId=versionResult.data.id,assets=publication.assets.map((asset:any)=>({...asset,design_version_id:versionId}));const assetResult=await admin.from('design_version_assets').upsert(assets,{onConflict:'design_version_id,sort_order'});if(assetResult.error)throw assetResult.error;const existing=await admin.from('design_version_assets').select('id,sort_order').eq('design_version_id',versionId);if(existing.error)throw existing.error;const expectedOrders=new Set(assets.map((asset:any)=>Number(asset.sort_order))),staleIds=(existing.data||[]).filter((asset:any)=>!expectedOrders.has(Number(asset.sort_order))).map((asset:any)=>asset.id);if(staleIds.length){const removed=await admin.from('design_version_assets').delete().in('id',staleIds);if(removed.error)throw removed.error}return true}
async function completeFrameworkRun(admin:any,row:any){const rows=(await groupRows(admin,row)).filter((item:any)=>['ready','confirmed'].includes(String(item.status))),publication=buildFormalVersionPublication({taskId:row.task_id,mode:mode(row),rows,creator:'Davis AI设计师'});if(!publication)return false;await publishFormalVersion(admin,publication);await admin.from('test_tasks').update({status:'pending_approval',summary_desc:'框架方案 v1 已完成，等待领导审核'}).eq('id',row.task_id);return true}
async function completeContentRevision(admin:any,row:any){const revision=(await admin.from('uat_content_revisions').select('*').eq('id',row.revision_id).single()).data;if(!revision)return false;const expected=(revision.affected_pages||[]).map(Number),rows=await groupRows(admin,row),ready=rows.filter((x:any)=>['ready','confirmed'].includes(String(x.status)));if(!expected.length||!expected.every((p:number)=>ready.some((x:any)=>Number(x.page_index)===p)))return false;const template=(await admin.from('uat_framework_templates').select('*').eq('id',revision.template_id).single()).data;if(!template)throw new Error('FRAMEWORK_TEMPLATE_REQUIRED');const priorVersion=(await admin.from('design_versions').select('id,status').eq('task_id',row.task_id).lt('version_no',Number(revision.revision_no)+1).order('version_no',{ascending:false}).limit(1).maybeSingle()).data;if(!priorVersion)throw new Error('PRIOR_FORMAL_VERSION_REQUIRED');const priorAssetsResult=await admin.from('design_version_assets').select('asset_url,sort_order').eq('design_version_id',priorVersion.id).order('sort_order',{ascending:true});if(priorAssetsResult.error)throw priorAssetsResult.error;const manifest=buildRevisionManifest(template.pages||[],revision.page_manifest||[],ready),description=String(revision.change_summary?.summary||revision.system_content||`完成第${revision.revision_no}次修改，提交需求方审核。`);const publication=buildFormalVersionPublication({taskId:row.task_id,mode:'content_revision',revisionNo:revision.revision_no,description,rows:ready,baseAssets:priorAssetsResult.data||[],creator:'Davis AI设计师'});if(!publication)return false;if(String(priorVersion.status)==='pending_review'){const accepted=await admin.from('design_versions').update({status:'accepted'}).eq('id',priorVersion.id);if(accepted.error)throw accepted.error}await publishFormalVersion(admin,publication);await admin.from('uat_content_revisions').update({status:'ready_for_review',page_manifest:manifest,generated_at:new Date().toISOString()}).eq('id',revision.id);await admin.from('test_tasks').update({status:'reviewing',summary_desc:`第${revision.revision_no}次修改已完成，等待需求方验收`}).eq('id',row.task_id);return true}

async function backfillOneFormalAsset(admin:any){const {data,error}=await admin.from('uat_design_generations').select('*').in('status',['ready','confirmed']).order('created_at',{ascending:true}).limit(30);if(error)throw error;const ready=(data||[]).filter(relevant),framework=ready.find((item:any)=>['initial_framework','framework_revision'].includes(mode(item))&&String(item?.output?.formal_asset_url||'').trim());if(framework){const existing=(await admin.from('design_versions').select('id').eq('task_id',framework.task_id).eq('version_no',1).maybeSingle()).data;if(!existing&&await completeFrameworkRun(admin,framework)){await audit(admin,'formal_delivery_version_backfilled',framework,{version_no:1});return{generation_id:framework.id,complete:true,version_no:1}}}const row=ready.find((item:any)=>!String(item?.output?.formal_asset_url||'').trim());if(!row)return null;const formalAssetUrl=await persistFormalAsset(admin,row,outputOf(row));const output={...outputOf(row),formal_asset_url:formalAssetUrl};const updated=await admin.from('uat_design_generations').update({output,updated_at:new Date().toISOString()}).eq('id',row.id);if(updated.error)throw updated.error;const complete=mode(row)==='content_revision'?await completeContentRevision(admin,{...row,output}):await completeFrameworkRun(admin,{...row,output});await audit(admin,'formal_delivery_asset_backfilled',row,{complete});return{generation_id:row.id,complete}}

async function markReady(admin:any,row:any,payload:any,page:any,pages:any[],refs:any[],assets:any[],inputs:any[]){const analysis=(await admin.from('uat_requirement_analyses').select('brief').eq('id',row.analysis_id).single()).data,size=resolveDemoSize(analysis?.brief||{}),m=mode(row),promptVersion=m==='content_revision'?TEMPLATE_REVISION_PROMPT_VERSION:DEMO_PROMPT_VERSION,formalAssetUrl=await persistFormalAsset(admin,row,payload),output={...outputOf(row),provider:'seedream',model:String(payload.model||row.model||SEEDREAM_DEMO_MODEL),image_url:String(payload.drive_url||payload.provider_url||''),provider_url:String(payload.provider_url||'')||null,formal_asset_url:formalAssetUrl,size,target_size:`${size.width}x${size.height}`,provider_size:String(payload.provider_requested_size||''),requested_size:String(payload.provider_requested_size||''),actual_size:String(payload.actual_size||''),dimension_match:true,input_image_count:Number(payload.input_image_count??inputs.length),drive_file_id:payload.drive_file_id||null,drive_url:payload.drive_url||null,drive_thumbnail_url:payload.drive_thumbnail_url||null,drive_folder_id:payload.drive_folder_id||null,drive_folder_url:payload.drive_folder_url||null,drive_file_name:payload.drive_file_name||null,drive_archive_status:'completed',persistent_storage:'google_drive',archive_namespace:archiveNamespace(row),usage:payload.usage||{},page_index:row.page_index,page_count:Number(row.page_count||pages.length),page_title:page.title,exact_copy:page.copy,prompt_version:promptVersion,style_reference_count:refs.length,design_asset_count:assets.length,model_input_count:inputs.length,failure_stage:null,next_attempt_at:null,worker_finished_at:new Date().toISOString()};await admin.from('uat_design_generations').update({status:'ready',error_message:null,output,usage:payload.usage||{},updated_at:new Date().toISOString()}).eq('id',row.id);const complete=m==='content_revision'?await completeContentRevision(admin,{...row,output}):await completeFrameworkRun(admin,{...row,output});if(!complete){const copy=m==='content_revision'?`内容改版 P${row.page_index} 已完成，等待其余受影响页面`:`框架 P${row.page_index} 已完成，后台继续下一页`;await admin.from('test_tasks').update({status:'processing',summary_desc:copy}).eq('id',row.task_id)}await audit(admin,'seedream_worker_page_ready',row,{drive_file_id:payload.drive_file_id,complete,archive_namespace:archiveNamespace(row),model:String(payload.model||row.model||'')});return{generation_id:row.id,page_index:row.page_index,status:'ready',complete}}

async function buildJob(admin:any,row:any){const [{data:analysis,error:aError},{data:refs,error:rError},{data:assets,error:dError}]=await Promise.all([admin.from('uat_requirement_analyses').select('*').eq('id',row.analysis_id).eq('task_id',row.task_id).single(),admin.from('uat_visual_references').select('id,file_name,data_url,note,is_primary,sort_order').eq('task_id',row.task_id).order('sort_order',{ascending:true}),admin.from('uat_design_assets').select('id,file_name,data_url,asset_role,note,sort_order').eq('task_id',row.task_id).order('sort_order',{ascending:true})]);if(aError||!analysis)throw new Error('ANALYSIS_NOT_FOUND');if(rError||dError)throw new Error((rError||dError)?.message||'GENERATION_INPUT_READ_FAILED');const analysisPages=selectGenerationPages(analysis.brief||{}),references=refs||[],required=assets||[],pageIndex=Number(row.page_index),m=mode(row);if(m==='content_revision'){const revision=(await admin.from('uat_content_revisions').select('*').eq('id',row.revision_id).single()).data,template=(await admin.from('uat_framework_templates').select('*').eq('id',row.template_id).single()).data;if(!revision||!template)throw new Error('CONTENT_REVISION_CONTEXT_MISSING');const templatePage=(template.pages||[]).find((x:any)=>Number(x.page_index)===pageIndex);if(!templatePage)throw new Error('TEMPLATE_PAGE_NOT_FOUND');const nextPage=analysisPages.find((p:any)=>Number(p.index)===pageIndex);if(!nextPage)throw new Error('REVISION_PAGE_NOT_FOUND');const anchor=await drivePreviewDataUrl(admin,String(templatePage.drive_file_id||'')),strategy=resolveGenerationStrategy({row,templatePage:{...templatePage,drive_preview_data_url:anchor},styleReferences:references,assets:required}),page={...nextPage,title:String(templatePage.page_title||nextPage.title)};return{analysis,pages:analysisPages,page,references,required,inputs:strategy.images.map((data_url:string,index:number)=>({data_url,input_kind:index===0?'template':index<=required.length?'asset':'style'})),prompt:buildTemplateRevisionPrompt({pageIndex,pageTitle:page.title,newCopy:page.copy,changeSummary:revision.change_summary,assets:required}),size:{width:Number(template.width||1242),height:Number(template.height||1660)}}}
  const page=analysisPages.find((p:any)=>Number(p.index)===pageIndex);if(!page)throw new Error('DEMO_PAGE_NOT_FOUND');const selected=selectModelInputs(references,required) as any[],styleReference=[...references].sort((a:any,b:any)=>Number(Boolean(b.is_primary))-Number(Boolean(a.is_primary))||Number(a.sort_order||0)-Number(b.sort_order||0))[0]||null;let prompt=buildCreativeDemoPrompt({brief:analysis.brief||{},page,styleReference,assets:required});if(m==='framework_revision'&&row.framework_adjustment_id){const adjustment=(await admin.from('uat_framework_adjustments').select('*').eq('id',row.framework_adjustment_id).single()).data;if(adjustment)prompt+=`\n\n【本轮框架调整要求｜最高优先级】\n领导原始意见：${String(adjustment.leader_feedback||'')}\n需求方与领导沟通后的明确执行要求：${String(adjustment.requester_direction||'')}\n${adjustment.supplemental_content?`补充业务内容：${String(adjustment.supplemental_content)}`:''}\n必须按需求方整理后的明确要求调整，不得自行猜测替代。`}
  return{analysis,pages:analysisPages,page,references,required,inputs:selected,prompt,size:resolveDemoSize(analysis.brief||{})}}

Deno.serve(async req=>{if(req.method!=='POST')return json({ok:false,error:'METHOD_NOT_ALLOWED'},405);const su=env('SUPABASE_URL'),sk=env('SUPABASE_SERVICE_ROLE_KEY');if(!su||!sk)return json({ok:false,error:'SERVER_ENV_MISSING'},500);const admin=createClient(su,sk,{auth:{persistSession:false,autoRefreshToken:false}}),secret=String(req.headers.get('x-seedream-worker-secret')||'').trim();const {data:authorized,error:authError}=await admin.rpc('validate_uat_seedream_worker_secret',{candidate:secret});if(authError||authorized!==true)return json({ok:false,error:'UNAUTHORIZED_WORKER'},401);
  const staleCutoff=new Date(Date.now()-STALE_MS).toISOString(),{data:staleAll}=await admin.from('uat_design_generations').select('*').in('model',SUPPORTED_MODELS).eq('status','generating').lt('updated_at',staleCutoff).limit(20);for(const row of (staleAll||[]).filter(relevant)){await finishFailure(admin,row,'WORKER_STALE_PROVIDER_STATE_UNKNOWN','worker_stale',{provider_state_unknown:true})}
  const {data:queuedAll,error:qError}=await admin.from('uat_design_generations').select('*').in('model',SUPPORTED_MODELS).eq('status','queued').order('created_at',{ascending:true}).limit(MAX_SCAN);if(qError)return json({ok:false,error:qError.message},500);const queued=(queuedAll||[]).filter(relevant);let candidate:any=null;for(const row of queued){if(!due(row))continue;if(await priorGroupReady(admin,row)){candidate=row;break}}if(!candidate){try{const backfilled=await backfillOneFormalAsset(admin);if(backfilled)return json({ok:true,processed:1,backfilled})}catch(error){return json({ok:false,error:error instanceof Error?error.message:String(error),stage:'formal_delivery_backfill'},500)}return json({ok:true,processed:0,queued:queued.length})}
  const {data:claimed,error:claimError}=await admin.from('uat_design_generations').update({status:'generating',error_message:null,output:{...outputOf(candidate),worker_started_at:new Date().toISOString()},updated_at:new Date().toISOString()}).eq('id',candidate.id).eq('status','queued').select('*').maybeSingle();if(claimError)return json({ok:false,error:claimError.message},500);if(!claimed)return json({ok:true,processed:0,skipped:'ALREADY_CLAIMED'});candidate=claimed;await audit(admin,'seedream_worker_page_started',candidate,{build:BUILD,archive_namespace:archiveNamespace(candidate),model:candidate.model});
  try{const job=await buildJob(admin,candidate),attempt=Number(outputOf(candidate).connect_attempts||0)+1,images=job.inputs.map((x:any)=>String(x.data_url||'')).filter(Boolean),archiveTaskId=archiveNamespace(candidate);let response:Response;try{response=await fetch(GATEWAY,{method:'POST',headers:{authorization:`Bearer ${sk}`,'x-seedream-worker-secret':secret,'content-type':'application/json'},body:JSON.stringify({action:'seedream.generate',model:String(candidate.model||SEEDREAM_DEMO_MODEL),task_id:archiveTaskId,page_index:candidate.page_index,page_count:Number(candidate.page_count||job.pages.length),width:job.size.width,height:job.size.height,prompt:job.prompt,images}),signal:AbortSignal.timeout(300000)})}catch(error){return json({ok:true,processed:1,result:await finishFailure(admin,candidate,`WORKER_GATEWAY_STATE_UNKNOWN:${error instanceof Error?error.message:String(error)}`,'worker_gateway',{provider_state_unknown:true,archive_namespace:archiveTaskId})})}
    const payload:any=await readJson(response);if(!response.ok||payload?.ok!==true){const message=String(payload?.error||`ARK_GATEWAY_HTTP_${response.status}`);if(isSafeConnectFailure(message)){const retry=safeConnectRetry(attempt);if(retry.retry){const output={...outputOf(candidate),connect_attempts:attempt,next_attempt_at:retry.next_attempt_at,last_connect_error:message,worker_last_attempt_at:new Date().toISOString(),archive_namespace:archiveTaskId};await admin.from('uat_design_generations').update({status:'queued',error_message:null,output,updated_at:new Date().toISOString()}).eq('id',candidate.id);await admin.from('test_tasks').update({status:'processing',summary_desc:`P${candidate.page_index} Ark 网络连接未建立，安全排队重连 ${attempt}/3；未进入计费生成`}).eq('id',candidate.task_id);await audit(admin,'seedream_worker_safe_connect_retry',candidate,{attempt,next_attempt_at:retry.next_attempt_at,archive_namespace:archiveTaskId});return json({ok:true,processed:1,result:{generation_id:candidate.id,status:'queued',safe_connect_retry:true,attempt,next_attempt_at:retry.next_attempt_at}})}return json({ok:true,processed:1,result:await finishFailure(admin,candidate,message,'ark_connect',{connect_attempts:attempt,archive_namespace:archiveTaskId})})}return json({ok:true,processed:1,result:await finishFailure(admin,candidate,message,'generation',{gateway_status:response.status,archive_namespace:archiveTaskId})})}
    if(!payload?.drive_file_id)return json({ok:true,processed:1,result:await finishFailure(admin,candidate,String(payload?.drive_error||'GOOGLE_DRIVE_ARCHIVE_FAILED'),'drive_archive',{provider_generated:true,provider_url:payload?.provider_url||null,drive_archive_status:'failed',archive_namespace:archiveTaskId})});return json({ok:true,processed:1,result:await markReady(admin,candidate,payload,job.page,job.pages,job.references,job.required,job.inputs)});
  }catch(error){return json({ok:true,processed:1,result:await finishFailure(admin,candidate,error instanceof Error?error.message:String(error),'worker')})}
});
