const DRIVE_TOKEN_URL='https://oauth2.googleapis.com/token';
const DRIVE_API='https://www.googleapis.com/drive/v3/files';
const DRIVE_UPLOAD_API='https://www.googleapis.com/upload/drive/v3/files';
const DRIVE_ROOT_FOLDER_ID='1vg12NJfXRXp8KBkvX8uh2RGTYmN0BPWu';
const BUCKET='designs';
function env(name:string){return String(Deno.env.get(name)||'').trim();}
function safe(value:unknown){return String(value||'task').replace(/[^a-zA-Z0-9._-]+/g,'-').slice(0,100)||'task';}
async function readJson(response:Response){const text=await response.text().catch(()=>"");if(!text)return{};try{return JSON.parse(text)}catch{return{raw:text}}}
export function driveConfig(){return {clientId:env('GOOGLE_CLIENT_ID'),clientSecret:env('GOOGLE_CLIENT_SECRET'),refreshToken:env('GOOGLE_REFRESH_TOKEN')};}
export function driveConfigured(){const c=driveConfig();return Boolean(c.clientId&&c.clientSecret&&c.refreshToken);}
async function accessToken(){const c=driveConfig();if(!c.clientId||!c.clientSecret||!c.refreshToken)throw new Error('GOOGLE_DRIVE_OAUTH_NOT_CONFIGURED');const response=await fetch(DRIVE_TOKEN_URL,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:c.clientId,client_secret:c.clientSecret,refresh_token:c.refreshToken,grant_type:'refresh_token'}),signal:AbortSignal.timeout(20000)});const payload=await readJson(response);if(!response.ok||!payload?.access_token)throw new Error(`GOOGLE_ACCESS_TOKEN_FAILED:${response.status}`);return String(payload.access_token);}
function q(value:string){return value.replace(/\\/g,'\\\\').replace(/'/g,"\\'");}
async function ensureFolder(token:string,taskId:string){const name=safe(taskId);const query=`'${DRIVE_ROOT_FOLDER_ID}' in parents and mimeType='application/vnd.google-apps.folder' and name='${q(name)}' and trashed=false`;const found=await fetch(`${DRIVE_API}?q=${encodeURIComponent(query)}&spaces=drive&fields=files(id,name,webViewLink)&pageSize=10`,{headers:{Authorization:`Bearer ${token}`},signal:AbortSignal.timeout(20000)});const payload=await readJson(found);if(!found.ok)throw new Error(`GOOGLE_DRIVE_FOLDER_SEARCH_FAILED:${found.status}`);if(Array.isArray(payload?.files)&&payload.files[0]?.id)return payload.files[0];const created=await fetch(`${DRIVE_API}?fields=id,name,webViewLink,parents`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify({name,mimeType:'application/vnd.google-apps.folder',parents:[DRIVE_ROOT_FOLDER_ID],appProperties:{davis_design_task_id:name}}),signal:AbortSignal.timeout(20000)});const folder=await readJson(created);if(!created.ok||!folder?.id)throw new Error(`GOOGLE_DRIVE_FOLDER_CREATE_FAILED:${created.status}`);return folder;}
export async function archiveStorageObject(admin:any,args:{taskId:string;pageIndex:number;storagePath:string;fileName?:string}){if(!driveConfigured())return {archived:false,status:'not_configured'};const token=await accessToken();const folder=await ensureFolder(token,args.taskId);const download=await admin.storage.from(BUCKET).download(args.storagePath);if(download.error||!download.data)throw new Error(`UAT_STORAGE_DOWNLOAD_FAILED:${download.error?.message||'missing'}`);const bytes=new Uint8Array(await download.data.arrayBuffer());const contentType=download.data.type||'image/jpeg';const ext=/png/i.test(contentType)?'png':'jpg';const name=args.fileName||`${safe(args.taskId)}_Page${String(args.pageIndex).padStart(2,'0')}_Seedream4_Demo.${ext}`;const init=await fetch(`${DRIVE_UPLOAD_API}?uploadType=resumable&supportsAllDrives=true&fields=id,name,mimeType,webViewLink,webContentLink,thumbnailLink,parents`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'content-type':'application/json; charset=UTF-8','X-Upload-Content-Type':contentType,'X-Upload-Content-Length':String(bytes.length)},body:JSON.stringify({name,mimeType:contentType,parents:[folder.id],appProperties:{davis_design_task_id:safe(args.taskId),page_index:String(args.pageIndex),provider:'seedream-4.0'}}),signal:AbortSignal.timeout(20000)});if(!init.ok)throw new Error(`GOOGLE_DRIVE_UPLOAD_INIT_FAILED:${init.status}`);const location=init.headers.get('location');if(!location)throw new Error('GOOGLE_DRIVE_RESUMABLE_LOCATION_MISSING');const uploaded=await fetch(location,{method:'PUT',headers:{'Content-Type':contentType,'Content-Length':String(bytes.length)},body:bytes,signal:AbortSignal.timeout(120000)});const file=await readJson(uploaded);if(!uploaded.ok||!file?.id)throw new Error(`GOOGLE_DRIVE_UPLOAD_FAILED:${uploaded.status}`);return {archived:true,status:'ready',drive_file_id:String(file.id),drive_file_name:String(file.name||name),drive_url:String(file.webViewLink||`https://drive.google.com/file/d/${file.id}/view`),drive_thumbnail_url:String(file.thumbnailLink||`https://drive.google.com/thumbnail?id=${file.id}&sz=w1200`),drive_folder_id:String(folder.id),drive_folder_url:String(folder.webViewLink||`https://drive.google.com/drive/folders/${folder.id}`)};}
