import { createClient } from 'npm:@supabase/supabase-js@2';
import { assertCanGenerateDemo, selectGenerationPages } from '../uat-ai-design/generation-service.ts';
import { SEEDREAM_DEMO_MODEL } from '../uat-ai-design/seedream-client.ts';
import { DEMO_PROMPT_VERSION } from './creative-prompt.ts';

const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,apikey,content-type,x-client-info','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json; charset=utf-8'};
const ALLOWED_EMAILS=new Set(['uat.requester@webank.com','davis.design.ai@webank.com','uat.leader@webank.com','uat.admin@webank.com']);
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const out=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:CORS});
function latestByPage(rows:any[]){const m=new Map<number,any>();for(const r of [...rows].sort((a,b)=>Date.parse(a.created_at||'')-Date.parse(b.created_at||'')))m.set(Number(r.page_index||1),r);return m}

Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:CORS});if(req.method!=='POST')return out({ok:false,error:'METHOD_NOT_ALLOWED'},405);const su=String(Deno.env.get('SUPABASE_URL')||'').trim(),sk=String(Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')||'').trim();if(!su||!sk)return out({ok:false,error:'UAT_SERVER_ENV_MISSING'},500);const admin=createClient(su,sk,{auth:{persistSession:false,autoRefreshToken:false}}),jwt=(req.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');const {data:auth}=await admin.auth.getUser(jwt),user=auth?.user;if(!user)return out({ok:false,error:'Authenticated UAT account required'},401);if(!ALLOWED_EMAILS.has(String(user.email||'').toLowerCase()))return out({ok:false,error:'UAT_CALLER_FORBIDDEN'},403);
  let body:any={};try{body=await req.json()}catch{return out({ok:false,error:'INVALID_JSON'},400)}const taskId=String(body.task_id||'').trim(),analysisId=String(body.analysis_id||'').trim(),firstKey=String(body.idempotency_key||'').trim(),runId=String(body.run_id||crypto.randomUUID()).trim(),startPage=Math.max(1,Number(body.page_index)||1);if(!taskId||!analysisId||!firstKey)return out({ok:false,error:'DEMO_PAGE_FIELDS_REQUIRED'},400);if(!UUID_RE.test(firstKey))return out({ok:false,error:'DEMO_PAGE_IDEMPOTENCY_KEY_MUST_BE_UUID'},400);
  const [{data:task},{data:analysis}]=await Promise.all([admin.from('test_tasks').select('*').eq('id',taskId).single(),admin.from('uat_requirement_analyses').select('*').eq('id',analysisId).eq('task_id',taskId).single()]);if(!task||task.assignee!=='davis.design.ai')return out({ok:false,error:'TASK_NOT_ASSIGNED_TO_AI'},400);if(!analysis)return out({ok:false,error:'ANALYSIS_NOT_FOUND'},400);try{assertCanGenerateDemo(String(analysis.status||''))}catch(error){return out({ok:false,error:error instanceof Error?error.message:String(error)},400)}const pages=selectGenerationPages(analysis.brief||{});if(!pages.some((p:any)=>Number(p.index)===startPage))return out({ok:false,error:'DEMO_PAGE_NOT_FOUND'},400);
  const {data:references,error:refError}=await admin.from('uat_visual_references').select('id').eq('task_id',taskId).limit(1);if(refError)return out({ok:false,error:refError.message},500);if((task.request_type==='平面视觉'||!task.request_type)&&!(references||[]).length)return out({ok:false,error:'VISUAL_REFERENCE_REQUIRED'},400);
  const {data:existing,error:eError}=await admin.from('uat_design_generations').select('*').eq('task_id',taskId).eq('analysis_id',analysisId).eq('kind','demo').eq('model',SEEDREAM_DEMO_MODEL).eq('prompt_version',DEMO_PROMPT_VERSION).order('created_at',{ascending:true});if(eError)return out({ok:false,error:eError.message},500);const latest=latestByPage(existing||[]),firstExisting=latest.get(startPage);if(firstExisting&&String(firstExisting.status)==='failed'&&firstExisting.output?.provider_generated===true&&String(firstExisting.output?.failure_stage||'')==='drive_archive')return out({ok:true,status:'archive_only_required',generation:firstExisting,archive_only_required:true});
  const queued:any[]=[];for(const page of pages.filter((p:any)=>Number(p.index)>=startPage)){const p=Number(page.index),current=latest.get(p);if(current&&['ready','confirmed'].includes(String(current.status)))continue;if(current&&['queued','generating'].includes(String(current.status))){queued.push(current);continue}const key=p===startPage?firstKey:crypto.randomUUID();const row=await admin.from('uat_design_generations').insert({task_id:taskId,analysis_id:analysisId,kind:'demo',model:SEEDREAM_DEMO_MODEL,prompt_version:DEMO_PROMPT_VERSION,idempotency_key:key,page_index:p,page_count:pages.length,status:'queued',output:{run_id:runId,queued_by:user.email,queue_version:'seedream-worker-v1',connect_attempts:0}}).select('*').single();if(row.error)return out({ok:false,error:row.error.message},500);queued.push(row.data)}
  if(!queued.length){const complete=pages.every((p:any)=>{const r=latest.get(Number(p.index));return r&&['ready','confirmed'].includes(String(r.status))});return out({ok:true,status:complete?'ready':'queued',complete,queued_pages:[]})}
  const pageLabels=queued.map(r=>`P${r.page_index}`).join('、');await admin.from('test_tasks').update({status:'ready_for_demo',summary_desc:`${pageLabels} 已进入 Seedream 后台队列；按页顺序执行，失败立即停止`}).eq('id',taskId);await admin.from('uat_audit_log').insert({actor_id:user.id,actor_email:user.email,action:'demo_pages_queued',task_id:taskId,details:{analysis_id:analysisId,run_id:runId,start_page:startPage,queued_pages:queued.map(r=>r.page_index),prompt_version:DEMO_PROMPT_VERSION}});return out({ok:true,status:'queued',run_id:runId,queued_pages:queued.map(r=>({id:r.id,page_index:r.page_index,status:r.status})),page_count:pages.length},202);
});
