import 'jsr:@supabase/functions-js/edge-runtime.d.ts';
import { createClient } from 'npm:@supabase/supabase-js@2';

const ARK_HOST='https://ark.cn-beijing.volces.com';
const SEEDREAM_ENDPOINT=`${ARK_HOST}/api/v3/images/generations`;
const SEEDANCE_CREATE_ENDPOINT=`${ARK_HOST}/api/v3/contents/generations/tasks`;
const SEEDREAM_MODEL='doubao-seedream-4-0-250828';
const SEEDREAM_PROVIDER_SIZE='1728x2304';
const STORAGE_BUCKET='designs';
const DRIVE_RELAY_URL='https://supffjeeouibhqdfqosk.supabase.co/functions/v1/uat-seedream-drive-relay';
const ALLOWED_EMAILS=new Set(['uat.requester@webank.com','davis.design.ai@webank.com','uat.leader@webank.com','uat.admin@webank.com']);
const CORS={'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'authorization,apikey,content-type,x-client-info','Access-Control-Allow-Methods':'POST,OPTIONS','Content-Type':'application/json; charset=utf-8'};
const encoder=new TextEncoder();

function out(body:unknown,status=200){return new Response(JSON.stringify(body),{status,headers:CORS});}
function env(name:string){return String(Deno.env.get(name)||'').trim();}
function safe(value:unknown){return String(value||'task').replace(/[^a-zA-Z0-9._-]+/g,'-').slice(0,100)||'task';}
async function readJsonSafe(response:Response){const text=await response.text().catch(()=>'');if(!text)return{};try{return JSON.parse(text)}catch{return{raw:text.slice(0,2000)}}}
function bytesFromBase64(value:string){const binary=atob(value);const bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);return bytes;}
async function relaySignature(secret:string){const key=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const signed=await crypto.subtle.sign('HMAC',key,encoder.encode('davis-seedream-drive-relay:v1'));return Array.from(new Uint8Array(signed),b=>b.toString(16).padStart(2,'0')).join('');}
async function authorizedUser(request:Request,admin:any){const jwt=(request.headers.get('Authorization')||'').replace(/^Bearer\s+/i,'');if(!jwt)throw new Error('UAT_JWT_REQUIRED');const {data,error}=await admin.auth.getUser(jwt);const user=data?.user;if(error||!user)throw new Error('UAT_JWT_INVALID');const email=String(user.email||'').toLowerCase();if(!ALLOWED_EMAILS.has(email))throw new Error('UAT_CALLER_FORBIDDEN');return{id:String(user.id),email};}
async function materializeImages(admin:any,taskId:string,values:unknown[]){const urls:string[]=[],paths:string[]=[];for(let i=0;i<Math.min(values.length,10);i++){const text=String(values[i]||'').trim();if(!text)continue;if(/^https?:\/\//i.test(text)){urls.push(text);continue;}const match=text.match(/^data:(image\/(?:jpeg|jpg|png));base64,(.+)$/s);if(!match)throw new Error('ARK_INPUT_IMAGE_FORMAT_INVALID');const mime=match[1].toLowerCase().replace('image/jpg','image/jpeg');const bytes=bytesFromBase64(match[2]);if(!bytes.length||bytes.length>10*1024*1024)throw new Error('ARK_INPUT_IMAGE_SIZE_INVALID');const ext=mime==='image/png'?'png':'jpg';const path=`uat-ark-inputs/${safe(taskId)}/${crypto.randomUUID()}-${String(i+1).padStart(2,'0')}.${ext}`;const upload=await admin.storage.from(STORAGE_BUCKET).upload(path,bytes,{contentType:mime,upsert:false,cacheControl:'300'});if(upload.error)throw new Error(`ARK_INPUT_UPLOAD_FAILED:${upload.error.message}`);paths.push(path);const signed=await admin.storage.from(STORAGE_BUCKET).createSignedUrl(path,1800);if(signed.error||!signed.data?.signedUrl)throw new Error(`ARK_INPUT_SIGN_FAILED:${signed.error?.message||'missing_url'}`);urls.push(String(signed.data.signedUrl));}return{urls,paths};}
async function cleanupPaths(admin:any,paths:string[]){if(!paths.length)return;const {error}=await admin.storage.from(STORAGE_BUCKET).remove(paths);if(error)console.error(JSON.stringify({event:'uat_ark_temp_cleanup_failed',error:error.message,count:paths.length}));}
function providerError(payload:any,status:number){const code=String(payload?.error?.code||payload?.code||`ARK_HTTP_${status}`);const message=String(payload?.error?.message||payload?.message||payload?.detail||'').replace(/\s+/g,' ').slice(0,600);const param=String(payload?.error?.param||payload?.param||'').slice(0,160);const requestId=String(payload?.request_id||payload?.requestId||payload?.error?.request_id||'').slice(0,160);return[code,param&&`param=${param}`,message&&`msg=${message}`,requestId&&`request_id=${requestId}`].filter(Boolean).join(':');}
async function archiveToDrive(arkKey:string,taskId:string,pageIndex:number,sourceUrl:string){const signature=await relaySignature(arkKey);const response=await fetch(DRIVE_RELAY_URL,{method:'POST',headers:{'content-type':'application/json','x-davis-relay-signature':signature},body:JSON.stringify({task_id:taskId,page_index:pageIndex,source_url:sourceUrl}),signal:AbortSignal.timeout(180_000)});const payload=await readJsonSafe(response);if(!response.ok||!payload?.ok)throw new Error(String(payload?.error||`DRIVE_RELAY_HTTP_${response.status}`));return payload;}
async function sourceUrlForLegacyRow(admin:any,row:any){const output=row?.output||{};const providerUrl=String(output.provider_url||'').trim();if(/^https?:\/\//i.test(providerUrl))return providerUrl;const storagePath=String(output.storage_path||'').trim();if(storagePath){const signed=await admin.storage.from(STORAGE_BUCKET).createSignedUrl(storagePath,900);if(signed.error||!signed.data?.signedUrl)throw new Error(`LEGACY_STORAGE_SIGN_FAILED:${signed.error?.message||'missing_url'}`);return String(signed.data.signedUrl);}const imageUrl=String(output.image_url||'').trim();if(/^https?:\/\//i.test(imageUrl))return imageUrl;throw new Error('ARCHIVE_SOURCE_MISSING');}
async function archiveExistingGeneration(admin:any,arkKey:string,generationId:string){const {data:row,error}=await admin.from('uat_design_generations').select('*').eq('id',generationId).single();if(error||!row)throw new Error('GENERATION_NOT_FOUND');const sourceUrl=await sourceUrlForLegacyRow(admin,row);const drive=await archiveToDrive(arkKey,String(row.task_id),Number(row.page_index||1),sourceUrl);const oldPath=String(row.output?.storage_path||'').trim();const output={...(row.output||{}),...drive,image_url:drive.drive_thumbnail_url||drive.drive_url,provider_url:row.output?.provider_url||null,storage_path:null,persistent_storage:'google_drive',drive_archive_status:'completed'};const {data:updated,error:updateError}=await admin.from('uat_design_generations').update({status:'ready',error_message:null,output,updated_at:new Date().toISOString()}).eq('id',row.id).select('*').single();if(updateError)throw updateError;if(oldPath)await cleanupPaths(admin,[oldPath]);return updated;}
async function probe(url:string,arkKey:string){const controller=new AbortController();const timer=setTimeout(()=>controller.abort('ark-probe-timeout'),10_000);const started=Date.now();try{const response=await fetch(url,{method:'GET',headers:{Authorization:`Bearer ${arkKey}`,'Content-Type':'application/json'},signal:controller.signal});return{reachable:true,status:response.status,elapsed_ms:Date.now()-started};}catch(error){return{reachable:false,status:0,elapsed_ms:Date.now()-started,error:error instanceof Error?error.message:String(error)}}finally{clearTimeout(timer)}}

Deno.serve(async(request:Request)=>{if(request.method==='OPTIONS')return new Response('ok',{headers:CORS});if(request.method!=='POST')return out({ok:false,error:'METHOD_NOT_ALLOWED'},405);const supabaseUrl=env('SUPABASE_URL'),serviceKey=env('SUPABASE_SERVICE_ROLE_KEY');if(!supabaseUrl||!serviceKey)return out({ok:false,error:'UAT_SERVER_ENV_MISSING'},500);const admin=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});try{const caller=await authorizedUser(request,admin);const body=await request.json().catch(()=>({}));const action=String(body?.action||'');const arkKey=env('ARK_API_KEY');if(action==='health'){const [seedream,seedance]=await Promise.all([probe(SEEDREAM_ENDPOINT,arkKey),probe(`${SEEDANCE_CREATE_ENDPOINT}/uat-health-check`,arkKey)]);return out({ok:seedream.reachable&&seedance.reachable&&Boolean(arkKey),ark_key_present:Boolean(arkKey),seedream,seedance});}if(!arkKey)return out({ok:false,error:'ARK_API_KEY_MISSING'},503);

if(action==='seedream.archive_existing'){const generationId=String(body?.generation_id||'').trim();if(!generationId)throw new Error('GENERATION_ID_REQUIRED');const generation=await archiveExistingGeneration(admin,arkKey,generationId);return out({ok:true,status:'ready',generation});}

if(action==='seedream.generate'){const prompt=String(body?.prompt||'').trim();if(!prompt)throw new Error('SEEDREAM_PROMPT_REQUIRED');const taskId=safe(body?.task_id),pageIndex=Math.max(1,Number(body?.page_index)||1);const materialized=await materializeImages(admin,taskId,Array.isArray(body?.images)?body.images:[]);try{const payload:Record<string,unknown>={model:SEEDREAM_MODEL,prompt:prompt.slice(0,5000),size:SEEDREAM_PROVIDER_SIZE,sequential_image_generation:'disabled',response_format:'url',stream:false,watermark:false};if(materialized.urls.length)payload.image=materialized.urls;const started=Date.now();let response:Response;try{response=await fetch(SEEDREAM_ENDPOINT,{method:'POST',headers:{Authorization:`Bearer ${arkKey}`,'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(180_000)});}catch(error){const message=error instanceof Error?error.message:String(error);console.error(JSON.stringify({event:'uat_ark_seedream_network_error',task_id:taskId,page_index:pageIndex,caller:caller.email,elapsed_ms:Date.now()-started,message}));return out({ok:false,error:`ARK_CONNECT_FAILED:${message}`},503);}const data=await readJsonSafe(response);if(!response.ok)return out({ok:false,error:`SEEDREAM_HTTP_${response.status}:${providerError(data,response.status)}`},response.status>=500?502:400);const first=Array.isArray(data?.data)?data.data[0]:null;const providerUrl=String(first?.url||'').trim();if(!providerUrl)throw new Error('SEEDREAM_OUTPUT_MISSING');let drive:any=null,driveError='';try{drive=await archiveToDrive(arkKey,taskId,pageIndex,providerUrl);}catch(error){driveError=error instanceof Error?error.message:String(error);}return out({ok:true,provider:'seedream',model:data?.model||SEEDREAM_MODEL,image_url:drive?.drive_thumbnail_url||providerUrl,provider_url:providerUrl,actual_size:String(first?.size||''),provider_requested_size:SEEDREAM_PROVIDER_SIZE,input_image_count:materialized.urls.length,usage:data?.usage||{},elapsed_ms:Date.now()-started,drive_file_id:drive?.drive_file_id||null,drive_url:drive?.drive_url||null,drive_thumbnail_url:drive?.drive_thumbnail_url||null,drive_folder_id:drive?.drive_folder_id||null,drive_folder_url:drive?.drive_folder_url||null,drive_file_name:drive?.drive_file_name||null,drive_archive_status:drive?.drive_file_id?'completed':'failed',drive_error:driveError||null});}finally{await cleanupPaths(admin,materialized.paths);}}

if(action==='seedance.submit'){const payload=body?.payload;if(!payload||typeof payload!=='object'||Array.isArray(payload))throw new Error('SEEDANCE_PAYLOAD_REQUIRED');const response=await fetch(SEEDANCE_CREATE_ENDPOINT,{method:'POST',headers:{Authorization:`Bearer ${arkKey}`,'Content-Type':'application/json'},body:JSON.stringify(payload),signal:AbortSignal.timeout(45_000)});const data=await readJsonSafe(response);if(!response.ok||!data?.id)return out({ok:false,error:`SEEDANCE_HTTP_${response.status}:${providerError(data,response.status)}`},response.status>=500?502:400);return out({ok:true,provider:'seedance',provider_task_id:String(data.id),response:data});}
if(action==='seedance.status'){const providerTaskId=safe(body?.provider_task_id);const response=await fetch(`${SEEDANCE_CREATE_ENDPOINT}/${encodeURIComponent(providerTaskId)}`,{method:'GET',headers:{Authorization:`Bearer ${arkKey}`,'Content-Type':'application/json'},signal:AbortSignal.timeout(35_000)});const data=await readJsonSafe(response);if(!response.ok)return out({ok:false,error:`SEEDANCE_STATUS_HTTP_${response.status}:${providerError(data,response.status)}`},response.status>=500?502:400);return out({ok:true,provider:'seedance',response:data});}
return out({ok:false,error:'ARK_GATEWAY_ACTION_INVALID'},400);}catch(error){const message=error instanceof Error?error.message:String(error);const status=/JWT|FORBIDDEN/.test(message)?401:/GOOGLE_|DRIVE_/.test(message)?502:400;return out({ok:false,error:message},status);}});
